/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "m3-schemes-on-primary-container": "var(--m3-schemes-on-primary-container)",
        "m3-schemes-on-surface": "var(--m3-schemes-on-surface)",
        "m3-schemes-outline-variant": "var(--m3-schemes-outline-variant)",
        "m3-schemes-primary": "var(--m3-schemes-primary)",
        "m3-schemes-primary-container": "var(--m3-schemes-primary-container)",
        "color-background-brand-hover": "var(--color-background-brand-hover)",
        "color-background-default-secondary": "var(--color-background-default-secondary)",
        "color-background-neutral-tertiary": "var(--color-background-neutral-tertiary)",
        "color-background-neutral-tertiary-hover": "var(--color-background-neutral-tertiary-hover)",
        "color-border-brand-default": "var(--color-border-brand-default)",
        "color-border-default-default": "var(--color-border-default-default)",
        "color-border-neutral-secondary": "var(--color-border-neutral-secondary)",
        "color-primitives-brand-800": "var(--color-primitives-brand-800)",
        "color-primitives-gray-100": "var(--color-primitives-gray-100)",
        "color-primitives-gray-300": "var(--color-primitives-gray-300)",
        "color-primitives-gray-500": "var(--color-primitives-gray-500)",
        "color-primitives-gray-900": "var(--color-primitives-gray-900)",
        "color-primitives-slate-300": "var(--color-primitives-slate-300)",
        "color-primitives-slate-600": "var(--color-primitives-slate-600)",
        "color-text-brand-on-brand": "var(--color-text-brand-on-brand)",
        "color-text-default-default": "var(--color-text-default-default)",
        "color-text-default-secondary": "var(--color-text-default-secondary)",
        "color-text-neutral-default": "var(--color-text-neutral-default)",
      },
      fontFamily: {
        "m3-body-medium": "var(--m3-body-medium-font-family)",
        "m3-title-medium": "var(--m3-title-medium-font-family)",
        "single-line-body-base": "var(--single-line-body-base-font-family)",
        subtitle: "var(--subtitle-font-family)",
        "title-hero": "var(--title-hero-font-family)",
        "title-page": "var(--title-page-font-family)",
      },
    },
  },
  plugins: [],
};